### ISSUE TITLE
Setup Application

### ISSUE THREAD

**Issue by glhewett** [wellsDev/groups_app#5]
- [x] Setup Rail Env
- [x] Create new rails application
- [x] Submit to github
- [x] Deploy to heroku

**Comment by glhewett** [comment]
- [ ] Create new rails application
- [ ] Submit to github
- [ ] Deploy to heroku

**Comment by glhewett** [comment]
@wellsDev, do you want to try and deploy to heroku?  Heroku's docs are really good, and it should be really easy.

https://devcenter.heroku.com/articles/getting-started-with-rails4

**Comment by wellsDev** [comment]
I quickly reviewed this and I have an heroku account setup.  I will take this on next

**Comment by wellsDev** [comment]
Deployed to heroku @ https://protected-castle-50815.herokuapp.com/

I did use the heroku tool belt in the command line and synced the app to the master branch

**Comment by glhewett** [comment]
👍
