### ISSUE TITLE
Integrate bootstrap

### ISSUE THREAD

**Issue by glhewett** [wellsDev/groups_app#6]

**Comment by glhewett** [comment]
You should probably use this project:

https://github.com/twbs/bootstrap-rubygem

**Comment by glhewett** [comment]
resist updating the entire app to use bootstrap.  That should happen as a result of the user stories.

**Comment by glhewett** [comment]
Once you get that integration, you should see if you can update the layouts/application view. I would copy and paste from [one of their examples.](http://getbootstrap.com/examples/starter-template/)

Don't remove the `<% content %>`.  You will need to put that in the place you want all of your content.

Please ask questions here.

**Comment by wellsDev** [comment]
Added Bootstrap 3 to the project following https://github.com/twbs/bootstrap-sass.  The layouts/application view was updated using the basic bootstrap template mentiioned. https://getbootstrap.com/examples/starter-template/

**Comment by wellsDev** [comment]
I updated the root route to show All Users to get a look at how the routes/controller/view is working

**Comment by wellsDev** [comment]
Thanks for being patient while I try to fight to get back to working on the app.

**Comment by glhewett** [comment]
Hi @wellsDev,  I don't see the code here on github. Did you do the work in a feature branch?  If so, go ahead and create a PR. We can then close this issue when the PR is merged. (this is done automagically if you put `fixes #x` in the bod of the PR)

 If not, go ahead and push.

**Comment by glhewett** [comment]
If you do not understand what I am asking, I can help you out, btw.
